In [2]:
import numpy as np
a_1 = np.arange(1,10,1)
print(a_1)

[1 2 3 4 5 6 7 8 9]


In [ ]:
a_2 = np.zeros([3,3])
print(a_2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a_3 = np.random.randint(1, 11, [5,5])
print(a_3)

[[2 3 2 2 6]
 [5 5 2 5 4]
 [2 9 3 8 5]
 [5 3 4 3 1]
 [1 3 8 1 4]]


In [ ]:
a_4 = np.random.ranf([4,4])
print(a_4)

[[0.22471509 0.96081314 0.83265635 0.51225401]
 [0.38135478 0.31621435 0.66975022 0.29941336]
 [0.41356259 0.29482885 0.02243978 0.46122953]
 [0.86747014 0.08829933 0.59878804 0.76949333]]


In [ ]:
a_5_1 = np.random.randint(1, 11, 5)
a_5_2 = np.random.randint(1, 11, 5)
print(f'a = {a_5_1}, b={a_5_2}')
sum = a_5_1 + a_5_2
print(f'a + b = {sum}')
subtr = a_5_1 - a_5_2
print(f'a - b = {subtr}')
mult = a_5_1 * a_5_2
print(f'a * b = {mult}')

a = [9 1 5 6 1], b=[2 6 3 3 3]
a + b = [11  7  8  9  4]
a - b = [ 7 -5  2  3 -2]
a * b = [18  6 15 18  3]


In [ ]:
a_6_1 = np.random.randint(1, 100, 7)
a_6_2 = np.random.randint(1, 100, 7)
print(f'a = {a_6_1}, b = {a_6_2}')
dot = np.dot(a_6_1, a_6_2)
print(f'a dot b = {dot}')

a = [51 84 79 76 74 46 74], b = [95 98 85  2 81 41 94]
a dot b = 34780


In [ ]:
a_7_1 = np.random.randint(1, 11, [2, 2])
a_7_2 = np.random.randint(1, 11, [2, 3])
print(f'a = {a_7_1}, b={a_7_2}')
mul_7 = np.dot(a_7_1, a_7_2)
print(f'a * b = {mul_7}')

a = [[9 4]
 [3 1]], b=[[2 6 2]
 [7 8 6]]
a * b = [[46 86 42]
 [13 26 12]]


In [ ]:
a_8 = np.random.randint(1, 11, [3, 3])
print(f'a = {a_8}')
inv = np.linalg.inv(a_8)
print(f'a inverted =  {inv}')

a = [[ 8  5  6]
 [10  5  5]
 [10  6  1]]
a inverted =  [[-0.41666667  0.51666667 -0.08333333]
 [ 0.66666667 -0.86666667  0.33333333]
 [ 0.16666667  0.03333333 -0.16666667]]


In [ ]:
a_9 = np.random.ranf([4, 4])
print(f'a = {a_9}')
transp = a_9.T
print(f'a trnasposed = {transp}')

a = [[0.35893061 0.10765222 0.86894137 0.13626965]
 [0.79730346 0.21844999 0.92805039 0.0318419 ]
 [0.92867638 0.33812815 0.07582818 0.50476084]
 [0.43413961 0.91115903 0.80420209 0.01411416]]
a trnasposed = [[0.35893061 0.79730346 0.92867638 0.43413961]
 [0.10765222 0.21844999 0.33812815 0.91115903]
 [0.86894137 0.92805039 0.07582818 0.80420209]
 [0.13626965 0.0318419  0.50476084 0.01411416]]


In [ ]:
a_10 = np.random.randint(1, 11, [3, 4])
v_10 = np.random.randint(1, 11, 4)
print(f'a = {a_10}')
print(f'v = {v_10}')
mult_10 = a_10 * v_10
print(f'a * v = {mult_10}')

a = [[1 8 8 4]
 [5 3 9 6]
 [8 7 9 1]]
v = [3 7 6 1]
a * v = [[ 3 56 48  4]
 [15 21 54  6]
 [24 49 54  1]]


In [ ]:
a_11 = np.random.ranf([2,3])
v_11 = np.random.ranf(3)
print(f'a = {a_11}')
print(f'v = {v_11}')
mult_11 = a_11 * v_11
print(f'a * v = {mult_11}')

a = [[0.40434773 0.32029851 0.4723784 ]
 [0.98167765 0.07736991 0.09738886]]
v = [0.4200946  0.48735453 0.05145849]
a * v = [[0.1698643  0.15609893 0.02430788]
 [0.41239748 0.03770658 0.00501148]]


In [ ]:
a_12_1 = np.random.randint(1, 11, [2, 2])
a_12_2 = np.random.randint(1, 11, [2, 2])
print(f'a_1 = {a_12_1}')
print(f'a_2 = {a_12_2}')
mult_12 = a_12_1 * a_12_2
print(f'a_1 * a_2 = {mult_12}')

a_1 = [[ 5 10]
 [ 7  5]]
a_2 = [[ 5  1]
 [10  3]]
[[25 10]
 [70 15]]


In [ ]:
a_13_1 = np.random.randint(1, 11, [2, 2])
a_13_2 = np.random.randint(1, 11, [2, 2])
print(f'a_1 = {a_13_1}')
print(f'a_2 = {a_13_2}')
mult_13 = np.dot(a_12_1, a_12_2)
print(mult_13)

a_1 = [[ 3  2]
 [10  7]]
a_2 = [[3 2]
 [3 7]]
[[125  35]
 [ 85  22]]


In [4]:
a_14 = np.random.randint(1, 101, [5, 5])
print(f'a = {a_14}')
sum_14 = a_14.sum()
print(f'sum of a = {sum_14}')

a = [[ 88  30  13 100  29]
 [  4  12   1  47  63]
 [ 94  94  21  52  91]
 [ 34  61  35  84  69]
 [ 11  61  51  27  95]]
sum of a = 1267


In [8]:
a_15_1 = np.random.randint(1, 11, [4, 4])
a_15_2 = np.random.randint(1, 11, [4, 4])
print(f'a_1 = {a_15_1}')
print(f'a_2 = {a_15_2}')
diff = a_15_1 - a_15_2
print(f'difference is {diff}')

a_1 = [[ 1  2  2 10]
 [ 1  4  2  1]
 [ 7  3  1 10]
 [ 8  6  6 10]]
a_2 = [[ 5  1  4  1]
 [10  9  4  7]
 [ 6  8  7  6]
 [ 3  8  7  8]]
difference is [[-4  1 -2  9]
 [-9 -5 -2 -6]
 [ 1 -5 -6  4]
 [ 5 -2 -1  2]]


In [13]:
a_16 = np.random.rand(3, 3)
print(f'a = {a_16}')
sum_16 = np.sum(a_16, axis=1)
col_vec = sum_16.reshape(-1,1)
print(f'arr rows sums in columns = {col_vec}')

a = [[0.6860594  0.15615375 0.51022503]
 [0.46887309 0.1169184  0.92025415]
 [0.8166915  0.51390761 0.93616485]]
arr rows sums in columns = [[1.35243818]
 [1.50604564]
 [2.26676397]]


In [15]:
a_17 = np.random.randint(1, 100, [3, 4])
print(f'array  = {a_17}')
a_17_sq = np.square(a_17)
print(f'array squared = {a_17_sq}')

array  = [[46 54 24 70]
 [61 12 61 77]
 [11 25  5 63]]
array squared = [[2116 2916  576 4900]
 [3721  144 3721 5929]
 [ 121  625   25 3969]]


In [20]:
v_18 = np.random.randint(1, 51, 4)
print(f'vector = {v_18}')
v_18_sqrt = np.sqrt(v_18)
print(f'vector square roots = {v_18_sqrt}')

vector = [27 50 17 38]
vector square roots = [5.19615242 7.07106781 4.12310563 6.164414  ]
